version: "3.8"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=StringPassw0rd!@
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:
